sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 4
before_script:
  - npm prune
  - npm i -g dont-break@^1.2.0
script:
  - npm test
  - npm run dont-break
after_success:
  - npm run semantic-release
  - npm run coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
